backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fotos", name: "photos", widget: "list", field: {label: "Foto", name: "image", widget: "image"}}
